// apps/web-nuxt/app/components/cms/ListEditor.vue
<template>
  <div class="space-y-4">
    <div v-for="(item, index) in items" :key="item.id" class="border border-slate-200 dark:border-slate-700 rounded-xl p-4 bg-white dark:bg-slate-800">
      <!-- Header -->
      <div class="flex justify-between items-center mb-4 pb-2 border-b border-slate-100 dark:border-slate-700">
        <h4 class="font-medium text-sm text-slate-500">Item #{{ index + 1 }}</h4>
        <div class="flex gap-1">
          <Button icon="pi pi-arrow-up" text rounded size="small" :disabled="index === 0" @click="moveItem(index, -1)" />
          <Button icon="pi pi-arrow-down" text rounded size="small" :disabled="index === items.length - 1" @click="moveItem(index, 1)" />
          <Button icon="pi pi-trash" text rounded severity="danger" size="small" @click="removeItem(index)" />
        </div>
      </div>

      <!-- Content -->
      <div class="grid gap-4">
        <!-- Title -->
        <div class="flex flex-col gap-2">
          <label class="text-sm font-medium text-slate-700 dark:text-slate-300">{{ titleLabel }}</label>
          <InputText v-model="item.title" @input="emitUpdate" placeholder="Judul item..." />
        </div>

        <!-- Description -->
        <div class="flex flex-col gap-2">
          <label class="text-sm font-medium text-slate-700 dark:text-slate-300">{{ descLabel }}</label>
          <Textarea v-model="item.description" rows="3" @input="emitUpdate" placeholder="Deskripsi..." />
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <!-- Icon Selection -->
          <div v-if="withIcon" class="flex flex-col gap-2">
            <label class="text-sm font-medium text-slate-700 dark:text-slate-300">Icon</label>
            <Select 
              v-model="item.icon" 
              :options="iconOptions" 
              optionLabel="label" 
              optionValue="value" 
              placeholder="Pilih Icon"
              @change="emitUpdate"
              class="w-full"
            >
              <template #value="slotProps">
                <div v-if="slotProps.value" class="flex items-center gap-2">
                  <span>{{ getIconEmoji(slotProps.value) }}</span>
                  <span>{{ slotProps.value }}</span>
                </div>
                <span v-else>{{ slotProps.placeholder }}</span>
              </template>
              <template #option="slotProps">
                <div class="flex items-center gap-2">
                  <span>{{ getIconEmoji(slotProps.option.value) }}</span>
                  <span>{{ slotProps.option.label }}</span>
                </div>
              </template>
            </Select>
          </div>

          <!-- Image URL -->
          <div class="flex flex-col gap-2">
            <label class="text-sm font-medium text-slate-700 dark:text-slate-300">{{ imageLabel }}</label>
            <InputText v-model="item.image_url" @input="emitUpdate" placeholder="https://..." />
          </div>
        </div>
      </div>
    </div>

    <!-- Add Button -->
    <Button label="Tambah Item Baru" icon="pi pi-plus" class="w-full" outlined severity="secondary" @click="addItem" />
  </div>
</template>

<script setup lang="ts">
interface ListItem {
  id: string
  title: string
  description: string
  image_url?: string
  icon?: string
}

const props = defineProps({
  modelValue: {
    type: String, // Expecting JSON string
    default: '[]'
  },
  titleLabel: { type: String, default: 'Judul' },
  descLabel: { type: String, default: 'Deskripsi' },
  imageLabel: { type: String, default: 'Image URL' },
  withIcon: { type: Boolean, default: true }
})

const emit = defineEmits(['update:modelValue'])

const items = ref<ListItem[]>([])

// Sync internal state with prop
watch(() => props.modelValue, (newVal) => {
  try {
    const parsed = JSON.parse(newVal || '[]')
    if (Array.isArray(parsed)) {
      // Only update if different to avoid cursor jumps / loops
      if (JSON.stringify(parsed) !== JSON.stringify(items.value)) {
        items.value = parsed.map(p => ({ ...p, id: p.id || String(Date.now() + Math.random()) }))
      }
    }
  } catch (e) {
    console.error('Failed to parse JSON', e)
    items.value = []
  }
}, { immediate: true })

function emitUpdate() {
  emit('update:modelValue', JSON.stringify(items.value))
}

function addItem() {
  items.value.push({
    id: String(Date.now()),
    title: '',
    description: '',
    icon: 'CheckCircle',
    image_url: ''
  })
  emitUpdate()
}

function removeItem(index: number) {
  items.value.splice(index, 1)
  emitUpdate()
}

function moveItem(index: number, direction: number) {
  const newIndex = index + direction
  if (newIndex >= 0 && newIndex < items.value.length) {
    const temp = items.value[index]
    items.value[index] = items.value[newIndex]
    items.value[newIndex] = temp
    emitUpdate()
  }
}

const iconOptions = [
  { value: "BookOpen", label: "Buku/Pendidikan" },
  { value: "Heart", label: "Hati/Karakter" },
  { value: "Sun", label: "Matahari/Tahfidz" },
  { value: "Users", label: "Orang/Pengajar" },
  { value: "Trophy", label: "Piala/Prestasi" },
  { value: "ShieldCheck", label: "Perisai/Aman" },
  { value: "Star", label: "Bintang" },
  { value: "Sparkles", label: "Kilau" },
  { value: "CheckCircle", label: "Centang" },
]

function getIconEmoji(iconName: string) {
  const map: Record<string, string> = {
    BookOpen: '📖',
    Heart: '❤️',
    Sun: '☀️',
    Users: '👥',
    Trophy: '🏆',
    ShieldCheck: '🛡️',
    Star: '⭐',
    Sparkles: '✨',
    CheckCircle: '✅'
  }
  return map[iconName] || '🔹'
}
</script>

// apps/web/components/dashboard/cms/ListEditor.tsx
"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Plus, Trash2, ArrowUp, ArrowDown, BookOpen, Heart, Sun, Users, Trophy, ShieldCheck, Star, Sparkles, CheckCircle } from "lucide-react"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

export interface ListItem {
    id: string
    title: string
    description: string
    image_url?: string
    icon?: string
}

interface ListEditorProps {
    value: string // JSON string
    onChange: (json: string) => void
    titleLabel?: string
    descLabel?: string
    imageLabel?: string
    withIcon?: boolean
}

const AVAILABLE_ICONS = [
    { value: "BookOpen", label: "Buku/Pendidikan", icon: BookOpen },
    { value: "Heart", label: "Hati/Karakter", icon: Heart },
    { value: "Sun", label: "Matahari/Tahfidz", icon: Sun },
    { value: "Users", label: "Orang/Pengajar", icon: Users },
    { value: "Trophy", label: "Piala/Prestasi", icon: Trophy },
    { value: "ShieldCheck", label: "Perisai/Aman", icon: ShieldCheck },
    { value: "Star", label: "Bintang", icon: Star },
    { value: "Sparkles", label: "Kilau", icon: Sparkles },
    { value: "CheckCircle", label: "Centang", icon: CheckCircle },
]

export function ListEditor({ value, onChange, titleLabel = "Title", descLabel = "Description", imageLabel = "Image URL", withIcon = true }: ListEditorProps) {
    const [items, setItems] = useState<ListItem[]>([])

    useEffect(() => {
        try {
            if (value) {
                const parsed = JSON.parse(value)
                if (Array.isArray(parsed)) {
                    setItems(parsed)
                }
            } else {
                setItems([])
            }
        } catch (e) {
            console.error("Failed to parse list JSON", e)
            setItems([])
        }
    }, [value])

    const updateItems = (newItems: ListItem[]) => {
        setItems(newItems)
        onChange(JSON.stringify(newItems))
    }

    const addItem = () => {
        const newItem: ListItem = {
            id: Date.now().toString(),
            title: "",
            description: "",
            image_url: "",
            icon: "CheckCircle"
        }
        updateItems([...items, newItem])
    }

    const remoteItem = (index: number) => {
        const newItems = [...items]
        newItems.splice(index, 1)
        updateItems(newItems)
    }

    const moveItem = (index: number, direction: 'up' | 'down') => {
        if (direction === 'up' && index === 0) return
        if (direction === 'down' && index === items.length - 1) return

        const newItems = [...items]
        const temp = newItems[index]
        newItems[index] = newItems[index + (direction === 'up' ? -1 : 1)]
        newItems[index + (direction === 'up' ? -1 : 1)] = temp
        updateItems(newItems)
    }

    const updateItemField = (index: number, field: keyof ListItem, val: string) => {
        const newItems = [...items]
        newItems[index] = { ...newItems[index], [field]: val }
        updateItems(newItems)
    }

    return (
        <div className="space-y-4">
            {items.map((item, index) => (
                <Card key={item.id} className="relative">
                    <CardHeader className="py-2 px-4 bg-muted/30 flex flex-row items-center justify-between">
                        <CardTitle className="text-sm font-medium">Item #{index + 1}</CardTitle>
                        <div className="flex gap-1">
                            <Button variant="ghost" size="icon" onClick={() => moveItem(index, 'up')} disabled={index === 0}>
                                <ArrowUp className="h-4 w-4" />
                            </Button>
                            <Button variant="ghost" size="icon" onClick={() => moveItem(index, 'down')} disabled={index === items.length - 1}>
                                <ArrowDown className="h-4 w-4" />
                            </Button>
                            <Button variant="ghost" size="icon" onClick={() => remoteItem(index)} className="text-red-500 hover:text-red-600 hover:bg-red-50">
                                <Trash2 className="h-4 w-4" />
                            </Button>
                        </div>
                    </CardHeader>
                    <CardContent className="p-4 space-y-3">
                        <div className="grid grid-cols-[1fr_auto] gap-4 items-start">
                            <div className="space-y-3">
                                <div className="grid gap-2">
                                    <Label>{titleLabel}</Label>
                                    <Input
                                        value={item.title}
                                        onChange={(e) => updateItemField(index, 'title', e.target.value)}
                                        placeholder="Enter title..."
                                    />
                                </div>
                                <div className="grid gap-2">
                                    <Label>{descLabel}</Label>
                                    <Textarea
                                        value={item.description}
                                        onChange={(e) => updateItemField(index, 'description', e.target.value)}
                                        placeholder="Enter description..."
                                        className="min-h-[80px]"
                                    />
                                </div>
                            </div>

                            {withIcon && (
                                <div className="w-32 space-y-2">
                                    <Label>Icon</Label>
                                    <Select
                                        value={item.icon || "CheckCircle"}
                                        onValueChange={(val) => updateItemField(index, 'icon', val)}
                                    >
                                        <SelectTrigger>
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {AVAILABLE_ICONS.map(icon => (
                                                <SelectItem key={icon.value} value={icon.value}>
                                                    <div className="flex items-center gap-2">
                                                        <icon.icon className="h-4 w-4" />
                                                        <span className="text-xs">{icon.label}</span>
                                                    </div>
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                    <div className="flex justify-center p-4 border rounded-md bg-slate-50">
                                        {(() => {
                                            const Icon = AVAILABLE_ICONS.find(i => i.value === item.icon)?.icon || CheckCircle
                                            return <Icon className="h-8 w-8 text-[var(--syuura-gold)]" />
                                        })()}
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className="grid gap-2">
                            <Label>{imageLabel}</Label>
                            <Input
                                value={item.image_url || ""}
                                onChange={(e) => updateItemField(index, 'image_url', e.target.value)}
                                placeholder="http://..."
                            />
                        </div>
                    </CardContent>
                </Card>
            ))}

            <Button type="button" variant="outline" onClick={addItem} className="w-full border-dashed">
                <Plus className="mr-2 h-4 w-4" /> Add Item
            </Button>
        </div>
    )
}
